{
    'name': 'LCS Product Catalog',
    'version': '19.0.2.6.0',
    'category': 'Sales',
    'summary': 'Dish master data, set menus, and SO set expansion with dish selection',
    'author': 'Recreatesys',
    'depends': ['sale', 'lcs_crm_catering'],
    'data': [
        'security/ir.model.access.csv',
        'data/master_dishes.xml',
        'data/mix_match_set.xml',
        'data/chinese_banquet_sets.xml',
        'data/canapes_only_set.xml',
        'data/western_buffet_set.xml',
        'data/chinese_buffet_set.xml',
        'data/cocktail_party_set.xml',
        'data/canape_box_set.xml',
        'data/sit_down_western_set.xml',
        'data/family_set.xml',
        'data/corporate_party_set.xml',
        'data/grand_opening_set.xml',
        'data/breakfast_refreshment.xml',
        'data/dim_sum.xml',
        'views/catering_set_views.xml',
        'views/sale_order_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
