from . import res_partner
from . import product_template
from . import crm_lead
from . import sale_order
from . import sale_waiter_line
from . import sale_hardware_line
from . import account_move
from . import mail_thread
from . import mail_compose_message
from . import res_users
from . import ir_http
