{
    'name': 'LCS CRM Catering',
    'version': '19.0.1.68.0',
    'category': 'Sales/CRM',
    'summary': 'Catering-specific fields for CRM, Sales Orders, and Invoices',
    'author': 'Recreatesys',
    'depends': ['crm', 'sale_crm', 'sale', 'account', 'hr', 'stock', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/paperformat.xml',
        'data/event_staff_job.xml',
        'data/waiter_service_product.xml',
        'data/free_delivery_product.xml',
        'data/hide_default_prints.xml',
        'views/res_partner_views.xml',
        'views/res_users_views.xml',
        'views/crm_lead_views.xml',
        'views/product_template_views.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/invoice_grouped_preview_template.xml',
        'views/mail_compose_message_views.xml',
        'report/invoice_report_template.xml',
        'report/sale_order_report_template.xml',
        'report/combined_quotation_report.xml',
        'wizard/combined_invoice_wizard_views.xml',
        'data/combined_invoice_action.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'lcs_crm_catering/static/src/css/chatter.css',
            'lcs_crm_catering/static/src/js/product_field_search_limit.js',
            'lcs_crm_catering/static/src/js/composer_cc.js',
            'lcs_crm_catering/static/src/xml/chatter_cc.xml',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
